# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1cf41ac75db9968e496d1f7bfca90273870c50064b40cf3fd7caaedb9969727ef9c15cca5306389b68f9ad1c476febbbfd9c4ff22685d889d0b7ad3a3d3f91c

test:
  secret_key_base: 44b6dceda57613d4c73d0e8ce7e0a9d44547735bbc363e6d4fe8bbfaafb9043acecd312c106084f4fbb60cccc65d53baef3ef73cac4fdf9a1d71c58615081bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
